### ISSUE TITLE
Starting Intero sometimes fails

### ISSUE THREAD

**Issue by michalrus** [michalrus/intero-nix-shim#1]
If you run, especially after changing `intero-nix-shim.cabal`:

```
% ./dogfood.sh exec -- intero --version
installing
Intero 0.1.20
% 
```

… sometimes, there’s this additional `installing` which is messing up `(intero-installed-p`) in `intero.el`.

I’ve set `--verbosity=0` for Cabal and `--quiet` for `nix-shell` everywhere, but it still happens.

Quick fix is to do `(intero-restart)` after such a failure.

On the other hand, this should not concern other projects using legitimate, precompiled `intero-nix-shim` from Nixpkgs, as there’ll be no `cabal run` and installing locally to `dist/` there.

**Comment by michalrus** [comment]
This `installing` needs to go, as it’s affecting other projects, as well.

Reproduction:

```
% intero-nix-shim exec -- intero --version
Intero 0.1.20
% intero-nix-shim exec -- intero --version
Intero 0.1.20
% intero-nix-shim exec -- intero --version
Intero 0.1.20
% intero-nix-shim exec -- intero --version
Intero 0.1.20
```
And now:
```
% echo >> kornel.cabal 
% intero-nix-shim exec -- intero --version
installing
Intero 0.1.20
% intero-nix-shim exec -- intero --version
Intero 0.1.20
% intero-nix-shim exec -- intero --version
Intero 0.1.20
% intero-nix-shim exec -- intero --version
Intero 0.1.20
% 
```

**Comment by shlevy** [comment]
@michalrus Any idea what tool it's coming from? You can pipe that tool's output into `/dev/null` if you don't need to parse it.

**Comment by michalrus** [comment]
No idea. :( I hoped it was some Nix script and that you might have known that. =)

But if not, I may have an idea… where to start investigating, will try today!

What would work, though, would be to ask Intero.el to throw `stderr` away, and use only `stdout`.

**Comment by shlevy** [comment]
nix tools are pretty good at printing debug messages to stderr instead of stdout, and I don't recognize that one :(

**Comment by michalrus** [comment]
Ok, it happens when a project is using the `callCabal2nix` function to auto-run `cabal2nix`. Hmmm.

It’s `showPhaseHeader()` from `generic/setup.sh`: https://github.com/NixOS/nixpkgs/blob/7daec8a234da5b097544dd4fb3fa1d2012870d08/pkgs/stdenv/generic/setup.sh#L827

Not cool. :crying_cat_face: I wonder why isn’t `--quiet` respected there.

I remember you suggesting to _not_ use `nix-shell --quiet`, but, first, I translated that old `/bin/sh` into Haskell more/less 1:1. Maybe let’s get rid of it now? =] But would it help with `generic/setup.sh`? =( Or maybe there is some other quick fix for now?

----------

Awww, there is:

```
     --no-build-output, -Q
         By default, output written by builders to standard
         output and standard error is echoed to the Nix command's
         standard error. This option suppresses this
         behaviour. Note that the builder's standard output and
         error are always written to a log file in
         prefix/nix/var/log/nix.
```

----------

No, that still doesn’t turn off phase headers. :(

**Comment by shlevy** [comment]
Why don't you just redirect stderr to dev null?

**Comment by michalrus** [comment]
But for all `stack exec`s? Or maybe a special case just for `stack exec -- intero --version`?

We’re using `exec(3)` after determining the final arguments list, but it should be doable. =)

~If not in pure Haskell, then `freopen("/dev/null", "w", stderr);` in C will do it.~ There’s `dup2` in `IODevice`.

**Comment by shlevy** [comment]
Why is stderr even being parsed at all?

**Comment by shlevy** [comment]
@michalrus Can you give me a minimal case of a nix command to call to create that line that you can't silence? This seems like a bug in nix if `-Q` isn't working.

**Comment by michalrus** [comment]
> Why is stderr even being parsed at all? 

Intero.el is using `(process-file PROGRAM &optional INFILE BUFFER DISPLAY &rest ARGS)` and it writes both STDERR and STDIN to its buffer.

> Can you give me a minimal case

I’ll try!

**Comment by michalrus** [comment]
@shlevy, run this script:

```shell
#!/bin/sh

cd $(mktemp -d)

touch project.cabal

echo '(import <nixpkgs> {}).haskellPackages.callCabal2nix "project" ./. {}' >default.nix

nix-build --quiet -Q
```

It’ll output:

```
installing
builder for ‘/nix/store/v57j4jnbqlw41gbm1bmx3y3hv9manvy6--.drv’ failed with exit code 1
```

**Comment by michalrus** [comment]
I’ll close this with redirecting STDERR to `/dev/null` for this single use (`stack exec intero -- --version`), but it should be fixed in Nix. I’ll report it there, as well.
